# Generated by Django 5.1.3 on 2024-12-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='uid',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
