# Generated by Django 5.1.3 on 2024-12-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
